### ISSUE TITLE
import cycle not allowed

### ISSUE THREAD

**Issue by caronc** [LINBIT/drbd-flexvolume#3]
I'm in the process of building an RPM for this package using CentOS 7.x and Go v1.9.4. Since this occurs in a virtual buildroot directory (and following RedHat standards) i can't just copy and paste your instructions.

I've done subtle changes such as the eliminating the reference to git:
```
# the top of the spec
%global githash 7c1ab4d

#...

%build
# Eliminate reference to git
sed -i -e 's/^\(VERSION\)=.*/\1=%{version}-%{githash}/g' Makefile

# Accommodate the directory structure Linbit hardcoded:
mkdir -p src/github.com/linbit/drbd-flexvolume/

# Move contents into dir:
find . -mindepth 1 -maxdepth 1 ! -name src \
    -exec %{__mv} {} src/github.com/linbit/drbd-flexvolume/ \;

# over-ride default paths to reference this buildroot path
export GOROOT="$(pwd)"
# /usr/lib/golang comes from golang-src rpm and has all of the
# dependencies used when building go packages. 
# $GOROOT is required to access hardcoded Linbit paths
export GOPATH="/usr/lib/golang:$GOROOT"

pushd src/github.com/linbit/drbd-flexvolume/
%{__make}
... fail...
```

Here is what happens during the build process:
```
...
/usr/bin/make
mkdir -pv _build  
mkdir: created directory '_build'
go build -ldflags "-X main.Version=7c1ab4d" -o _build/drbd drbd/main.go
import cycle not allowed
package main
	imports fmt
	imports errors
	imports runtime
	imports runtime/internal/atomic
	imports unsafe
	imports runtime
import cycle not allowed
package main
	imports log/syslog
	imports net
	imports runtime/cgo
	imports runtime/cgo
make: *** [build] Error 1
```

I have a basic understanding of what is going on from [this stackoverflow](https://stackoverflow.com/questions/28256923/import-cycle-not-allowed) post.  But i'm not a _Go_ developer, so i thought i'd ask you guys first.

Any suggestions?

**Comment by rck** [comment]
Hi, this project uses "drbdmanage" which is EoL and is replaced with LINSTOR, the new SDS solution. Please use the new [linstor-flexvolume](https://github.com/LINBIT/linstor-flexvolume) project. This new project also has a packaging branch. Expect this branch to be rebased/force pushed, we are currently working on it, but it produces debs and rpms.

So, sorry, you are too late to the party, please move along to the LINSTOR based projects.
